### ISSUE TITLE
[Requested feature] APIs docs

### ISSUE THREAD

**Issue by tran-huy-phuc** [app-generator/rocket-django#18]
Because the template supports APIs, we definitely need APIs docs like Swagger @app-generator

**Comment by app-generator** [comment]
Hello @thphuc 

The API docs are available in the release [v0.0.12](https://github.com/app-generator/rocket-django/releases)

Please check

**Comment by tran-huy-phuc** [comment]
Thanks @app-generator. Awsome!

**Comment by app-generator** [comment]
Yw @thphuc 

In case you have the time, let us know how can we improve the product.
