### ISSUE TITLE
Use HTMX to build template

### ISSUE THREAD

**Issue by tran-huy-phuc** [app-generator/rocket-django#21]
Hi @app-generator 

Can you update the readme to guide us how to use htmx?

**Comment by app-generator** [comment]
Hello @thphuc.

Soon we will provide a page/route that uses htmx.

TY!

**Comment by tran-huy-phuc** [comment]
Sounds good. Thanks @app-generator

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
