### ISSUE TITLE
[DOCS] Charts - Missing insights on the Code

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-django#22]
The doc should explain to the users:

- Where the code is located
- How the Model information is prepared 
- How the view presents the data to the user
  - JS
  - HTML

@BenFaruna please take a look.

TY!

**Comment by BenFaruna** [comment]
Alright, I will do that

**Comment by app-generator** [comment]
Hello @BenFaruna 

Please take a look at the charts section and split the information a suggested below:

- charts-template-view.md
  - this should explain the pattern used to showcase the information mostly using server-side
- charts-api.md
  - this should explain how the feature was coded using DRF & JS 

  Thank you!

**Comment by BenFaruna** [comment]
Okay, I will do that

**Comment by app-generator** [comment]
Validated. Ty @BenFaruna
