### ISSUE TITLE
[DOCS] CI/CD - Deploy with Render

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-django#23]
The starter can be deployed in seconds on Render, a popular deployment service

- Intro About Render
- Mention and explain `render.yaml`
- Mention and explain `build.sh` 

@BenFaruna please take a look. 

TY!

<br />

> Render Settings: 

![image](https://github.com/app-generator/rocket-django/assets/51070104/8db2e54a-f609-4149-ab0e-7d7051d8baff)

---

![image](https://github.com/app-generator/rocket-django/assets/51070104/6ecc3ae2-2289-4000-aaa3-4a464f116973)

**Comment by BenFaruna** [comment]
Okay, I'll work on that next once I'm done with charts and data tables

**Comment by app-generator** [comment]
Yep .. one by one.
Ty B!

**Comment by app-generator** [comment]
Validated. TY @BenFaruna
