### ISSUE TITLE
The icon appears very large on the screen.

### ISSUE THREAD

**Issue by soimkim** [app-generator/rocket-django#39]
![image](https://github.com/app-generator/rocket-django/assets/4284712/b1e557f1-f858-4725-a054-c52359b87f72)
When I install and run python 3.8, node v22.2.0, the screen appears as above.
Did I set something wrong?

**Comment by soimkim** [comment]
It was because I didn't build it...

**Comment by app-generator** [comment]
Hello @soimkim 

This might be related to the `DEBUG=False` that requires `collectstatic` to be executed 

Let us know if you need further assistance.
