### ISSUE TITLE
Manage Colors in the project

### ISSUE THREAD

**Issue by app-generator** [app-generator/rocket-django#40]
> more input needed

**Comment by HenriqueRibeiroMilech** [comment]
Hello, here’s the situation: I need to change the colors of the existing Rocket templates, but whenever I try to change a background color, it only lets me use a few colors that I believe were predefined for Rocket. So, I need to add other colors to customize my project.

The image I attached shows one of the colors I need to customize.
![Captura de tela 2024-08-26 115152](https://github.com/user-attachments/assets/06c03ca8-5ebb-4d2f-ac5d-2818d124bf0c)

**Comment by app-generator** [comment]
Hello @HenriqueRibeiroMilech 

What you need is more like a theming: primary/secondary color that applies to all pages. 

If this is the case (please confirm) is a new request. We need to find a solution. 

TY!

**Comment by HenriqueRibeiroMilech** [comment]
No, I need to be able to change the colors of the project. For example, I want to change the background color of a page, but it only lets me change to some specific colors. I want to be able to add and change to the colors I want.

**Comment by app-generator** [comment]
Noted @HenriqueRibeiroMilech 

Let us get back with a customization scenario.

**Comment by gemini774** [comment]
Hello @HenriqueRibeiroMilech ,

Here is the steps:
- Run `npm i` or `yarn`
- Run `npm run dev` or `yarn run dev`

And try to hard refresh your page with `ctlr+shift+r`.

**Comment by ghost** [comment]
Hello @HenriqueRibeiroMilech ,

Here is the steps:
- `npm i` or `yarn` to install the dependencies.
- `npm run dev` or `yarn run dev`

And try to hard refresh your page with `ctrl+shift+r`

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
